model/mod_list.py
model/mod_list_item.py

For an unknown reason the bundled app on MacOS isn't able to display the icons in the data folder, even though it is included in the MacOS package contents. It worked fine on Windows. This PR uses the same method of referencing the `style.qss` with the icons. Tested to work on both Windows and Mac bundled apps.

Fixing path to icons on bundled app MacOS

---

sub_view/active_mods_panel.py
sub_view/inactive_mods_panel.py
util/mods.py
view/game_configuration_panel.py
view/main_content_panel.py

A number of small improvements and fixes following feedback from the Alpha 1.0.1 release (thanks LM!). The following list of changes were made:
- Autodetect on Mac now goes into the `RimWorldMac.app/Mods` folder. Nothing was changed with how local mods are actually collected. The issue was that the previous local mods path for Mac was set to the game folder, where there are no mods. Getting local mods on Mac should now work.
- Some About.xml files have weird `MayRequire` tags, which we were able to parse fine for dependencies but crashed on load rules. Load rules should now work for this.
- Search bars now filter for package_ids in addition to names
- Version mismatch errors are now surfaced on mod list items and warnings/error summary
- Warnings/errors are now differentiated a bit more; …

Alpha 1.0.1 patches

---

app.py
model/animation_label.py
model/mod_list.py
model/mod_list_item.py
model/scroll_label.py
panel/settings_panel.py
setup.cfg
sort/dependencies.py
sort/rimpy_sort.py
sort/topo_sort.py
sub_view/actions_panel.py
sub_view/active_mods_panel.py
sub_view/inactive_mods_panel.py
sub_view/mod_info_panel.py
util/error.py
util/mods.py
util/proxy_style.py
util/xml.py
view/game_configuration_panel.py
view/main_content_panel.py
view/status_panel.py

This PR does two main things:
* First, it gets rid of star imports, which is a bad practice
* Second, it adds type annotations where necessary, to be compliant with `mypy`. A new `setup.cfg` contains the `mypy` configuration.
This PR also moves the project up Python versions, to 3.9 or greater. This is because some typing annotations that were added here use the new subscript-able built-in types.
The goal here is to make the project cleaner and easier for new contributors to work with.

Refactoring and mypy compliance

---

view/game_configuration_panel.py
view/main_content_panel.py

re fix #52 
the issue don't seem to appear on linux, its an issue with the windows file manager who add the .xml after selection the file i think

Fix .xml extension issues exporting, fix typo in import func, addt'l autodetect paths for Linux

---

.vscode/settings.json
sub_view/active_mods_panel.py

There's a bug where `loadAfter` and `loadBefore` violations aren't showing in the UI as warning/error labels (on individual mod cells and also on the warnings/error summary). This was due to code looking in a `uuid`-keyed dict for mods with package IDs. I've made a small fix so we're looking in the right place.
Manual testing and verification through running RimSort locally and dragging around mods

[FIX] bugfix for missing loadAfter/loadBefore warnings on the UI

---

README.md

Updated the URL of the Discord logo in the README.md file to fix a malfunctioning Discord invitation link

Update Discord logo URL in README.md

---

util/generic.py

On the Mac, under Python 3.9, the method call `webbrowser.get().name` fails with an OS-level error:
```
>>> import webbrowser
>>> webbrowser.get().name
File "<stdin>", line 1, in <module>
AttributeError: 'MacOSXOSAScript' object has no attribute 'name'
```
This problem goes away under Python 3.11, but I think a better fix would be to remove the call entirely, as on the Mac it just returns `"default"` and on Windows it returns an empty string. So it's kind of pointless.
This PR removes the `webbrowser.get().name` call entirely and rewords the docstring and log message text to be generic. Now it works identically on macOS and Windows.

Fix open_url_browser function which malfunctions on macOS under Python 3.9

---

util/steam/steamcmd/wrapper.py

I believe this fixes #189 and allows for spaces in the relevant paths.

Added quotes to download_mods() in steamcmd/wrapper.py

---

.gitignore

- Uncommented previously commented-out `.idea/` line to ignore PyCharm user-specific IDE config files
- Removed `*.xml` line which is no longer necessary now that `.idea/` is ignored

Updated .gitignore for PyCharm IDE users

---

RimSort.py
controller/menu_bar_controller.py
controller/settings_controller.py
model/settings.py
util/system_info.py
view/game_configuration_panel.py
view/menu_bar.py

- Add a view class with different menu bars for macOS and non-macOS users
- Add a controller class to handle the menu bar's signals
- Implement view and controller as members of MainWindow
- Add a SystemInfo class to neatly distinguish between operating systems and architectures (used for the conditional logic in the MenuBar view class)

Add a basic menu bar to the app

---

sub_view/actions_panel.py

They're in the menu bar now so the MainWindow buttons are redundant

Remove import & export buttons from MainWindow

---

util/app_info.py

The path was accidentally set to the wrong location on Windows only in PR #202

Fix the path to the user data directory

---

RimSort.py
util/app_info.py
view/main_window.py

- added an app_data_folder property to AppInfo that points to the `data` folder location
- refactored `MainWindow` into its own Python module and out of `RimSort.py`
- renamed some previously private methods in `MainWindow` to public methods because they're being called outside the class
- `RimSort.py` and `main_window.py` now both pass mypy, which the exception of `logger_tt` lacking type stubs
Tested on macOS 14 and Windows 11.

Clean up RimSort.py

---

model/mod_list.py
model/mod_list_item.py
sort/alphabetical_sort.py
sort/dependencies.py
sort/topo_sort.py
sub_view/active_mods_panel.py
sub_view/inactive_mods_panel.py
util/metadata.py
view/main_content_panel.py

With this PR, the app will no longer store metadata inside mods list items. We rely on an ordered list of UUIDs to be utilized with MetadataManager for metadata-related interactions.
**Following functionality is affected with this PR:**
- General mods list interactions (e.g., moving mods between lists)
- Clearing mods
- Restoring mods
- Sorting mod list
- Saving mod list
- todds optimize without active mods target checked
- Export mod list to XML
- Export mod list to clipboard
- Share mod list via Rentry
- Recalculate active mods list errors/warnings

Refactor application to rely on UUIDs, optimizations

---

view/menu_bar.py

Also change the shortcut ⌃S / ⌘S to ⇧⌃S / ⇧⌘S, as is standard for a "Save As…" menu item.
This change will keep the menu bar "Save" item (write to a user-specified XML file) from overlapping with the main window's "Save" button (write to RimWorld's `ModsConfig.xml` file).

Change "Save Mod List…" menu item to "Save Mod List As…"

---

controller/settings_controller.py
util/generic.py
view/settings_dialog.py

Per user request, the Locations tab now has "Open…" buttons which open their corresponding locations in the operating system's file manager.

Add "Open…" buttons to Locations tab

---

view/menu_bar.py

Due to a limitation in Qt 6.6.0, the keyboard shortcut doesn't appear under the Mac's application menu. It's active and it works, but it's not shown in the menu as a valid keyboard shortcut.
I'm putting this in the "better than nothing" category at this time. Ideally a future update to Qt will fix the problem without our having to change anything.
Closes #218

Add ⌘-comma/⌃-comma shortcuts for opening the Settings dialog to the menu bars

---

app/views/menu_bar.py

RimSort on MacOS is not starting because `upload_rimsort_old_log_action` is not properly instantiated upon MenuBar creation for MacOS.

[Hotfix] RimSort is not starting on MacOS

---

app/views/mods_panel.py

There is currently an edge case where if you click back and forth between the same two mods, one on the inactive mods panel and one on the active mods panel, the ModInfo panel does not update accordingly. This is because we're currently using the `currentItemChanged` hook and technically the item does not change in the context of a single mod panel. So, I'm adding the `itemClicked` hook to account for this edge case.
Technically, this means when you click an item the ModInfo panel is actually updated twice, but the work done during a single update is minimal so I think this is worth the QoL improvement.

[QOL] Improving functionality clicking on mods

---

app/utils/metadata.py

Fixes issues with mods which have assemblies .dll or file in the root dir
i had encountered the below issue
[ERROR][2024-04-14 13:35:24][14492][Dummy-10][metadata][run][1486] : NotADirectoryError: [WinError 267] The directory name is invalid: 'G:\\Games\\RimWorld\\Mods\\2916253559\\Assemblies'
File "E:\Github\RimSort_Main\app\utils\metadata.py", line 1480, in run
mod_metadata = self.__parse_mod_data(
^^^^^^^^^^^^^^^^^^^^^^
File "E:\Github\RimSort_Main\app\utils\metadata.py", line 1336, in __parse_mod_data
for filename in os.listdir(assemblies_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] The directory name is invalid: 'G:\\Games\\RimWorld\\Mods\\2916253559\\Assemblies'

Fix and Improve Assembly Detection

---

app/views/main_content_panel.py
app/views/mods_panel.py

This introduces a functional "lazy-loading" for `ModListItemInner`
While unmeasured by me, you can observe a significant improvement in performance inside the app. Item widgets will not be created unless their parent items are visible.
Additional support has been added for search filter support as well

Implement lazy loading for `ModListItemInner`

---

app/views/main_content_panel.py

fix
Error:
File "C:\Users\Nossea\DOWNLO~1\RIMSOR~1\RimSort\app\views\main_content_panel.py", line 2294, in _do_clone_repo_to_path
NameError: name 'Repo' is not defined
During handling of the above exception, another exception occurred:
File "C:\Users\Nossea\DOWNLO~1\RIMSOR~1\RimSort\app\views\main_content_panel.py", line 3186, in _on_do_download_steam_workshop_db_from_github
File "C:\Users\Nossea\DOWNLO~1\RIMSOR~1\RimSort\app\views\main_content_panel.py", line 2300, in _do_clone_repo_to_path
NameError: name 'GitCommandError' is not defined

Do not Prosses if Git Does not exists

---

.github/workflows/auto_build.yml
.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
distribute.py

Add GitHub attestation to the build pipeline for the executable and the zipped artifact.
Includes bump to the linter version and also a temporary ignore for the GitHub Actions linter to ignore not recognizing the attestations permission.

Artifact attestation

---

.vscode/settings.json
app/views/main_content_panel.py
pyproject.toml
requirements_develop.txt

Adds to the popup dialogue as well as the log warning that the app needs to be restarted after installing Git in order for the path changes to take effect.

Add warning to restart the app on git install

---

app/__main__.py
app/controllers/settings_controller.py
app/models/settings.py
app/utils/metadata.py
app/utils/steam/steamcmd/wrapper.py
app/utils/steam/webapi/wrapper.py
app/utils/system_info.py
app/utils/watchdog.py
app/views/main_window.py
app/windows/rule_editor_panel.py
requirements_develop.txt

eliminate ruff related complaints

Format with ruff

---

app/controllers/settings_controller.py

Fixes an incorrect type crash observed when opening settings in a new instance/setting up a new instance
This is mostly just a quick patch. Should seriously consider reworking how settings are handled so that these kinds of bugs are rarer/impossible.

Fix crash on opening settings with a new instance

---

app/__main__.py

Remove the update scripts from builds to prevent users from using the deprecated scripts

remove deprecated update scripts from builds

---

app/views/main_content_panel.py

Patch to fix 'Repo' is not defined crash when Git is not installed.

fix repo is not defined crash

---

app/models/settings.py
app/views/main_content_panel.py

Making handling of run_args agnostic as to if it is a string or list
"run_args" in the settings controller seems to be sometimes a string and sometimes a list of strings. Will likely fix the consistency later on through the metadata rework but for now this ensures agnostic handling.

Fix passing run_args on run

---

app/utils/schema.py

Graceful fail if exception, such as if the mods_config_data is None for some reason, when validating mod lists. 
Gives a warning to the user instead of a vague hard crash that is difficult to self diagnose.

Graceful fail if exception when validating mods list

---

app/views/mods_panel.py

Small improvements for the "toggle warning icon" feature:
- Adding debug statement when a toggle happens
- Toggling "off" the last warning while errors exist (or the last error while warnings exist) does not remove the summary text for warnings (or errors) due to the if/else logic. Fixing so this is behaving as expected.
- Toggling "off" version mismatch errors does not remove the summary text due to missing a condition. Fixing so this is behaving as expected.
Testing: manually tested on my Windows machine

[417] toggle warnings icon fixes

---

.github/labeler.yml

Add auto label for dependencies label based on "requirements*.txt" glob.
Remove "requirements*.txt" glob from DevOps label.

add dependencies label

---

app/controllers/app_controller.py
app/sort/dependencies.py
app/utils/constants.py
app/utils/rentry/wrapper.py
app/utils/steam/steamworks/wrapper.py
app/views/mods_panel.py

An initial solution for supporting mod replacements, e.g. Prepatcher can be substituted for Harmony. The solution maintains a dictionary in `constants.py` that maps mods to a list of replacement mods. During warning/error calculation, if mod A depends on mod B but mod B doesn't exist in the mod list, we check if any of mod B's replacements exist in the mod list (note: specific to active or inactive, not both). This way, having Prepatcher but not Harmony will not show warnings for all the mods that depend on Harmony.
NOTE: this change does NOT enforce load order for mod replacements. i.e. if mod A, through some load order rules, would end up being loaded somewhere between some other mods, but we replace it with mod B, there is no guarantee that mod B will be loaded in the same spot; mod B …

[418] support mod replacements

---

app/__main__.py
app/utils/obfuscate_message.py
requirements_develop.txt
tests/utils/test_obfuscate_message.py

This PR implements #427
It uses a regular expression to try to find the user in a path and replaces it with '...'
I've included some pytests.
Works for both Windows and Unix, though I've only tested on a Windows (NTFS) system. Pytests include unix style paths. It is drive agnostic.
There may be some edge cases, but this should catch the username in 99% of cases. Note that if someone names a folder other than the user folder their name, there isn't much that can be done there.
It does not filter out unix sudo paths since those are all the same as far as I know and there is no identifying info.
This PR also adds pytest as a develop dependency

Obfuscate user in paths

---

.github/ISSUE_TEMPLATE/bug_report.md

Modifies the issue bug report template to add a question about the processor architecture, what sort method they are using if applicable, and also asks the user to first check if their issue had already been reported.

Add arch, duplicate issue and sort method question

---

app/controllers/menu_bar_controller.py
app/views/menu_bar.py

Refactored `menu_bar.py`
- individual menus are separated into their own method
- single menu creation method for both mac and non-mac
- settings and quit actions are on the App menu for mac and on the File menu for non-mac
- on mac, moved update stuff to Help menu to be consistent with non-mac
Tested on Mac and Windows

Refactor menu bar

---

app/windows/rule_editor_panel.py

Addressing https://github.com/RimSort/RimSort/issues/477
Checking for duplicate rules is incorrectly using substring check rather than equivalence check, resulting in cases where mods with package ids sharing substrings are marked as duplicate. Fixing so we're checking for string equivalence.
Example case: add WMBP More Vanilla Biomes `carolusclen.dlc.wmbp.mvb` first, and then WMBP Alpha Biomes `carolusclen.dlc.wmbp`. This is fixed through this PR. Genuine duplicate rules are still detected.

[477] fix rule editor equivalence check bug

---

app/controllers/menu_bar_controller.py
app/utils/event_bus.py
app/utils/steam/steamworks/wrapper.py
app/views/main_content_panel.py
app/views/menu_bar.py
app/views/mods_panel.py

Changes for https://github.com/RimSort/RimSort/issues/436
Adds four new menu buttons, under `File -> Shortcuts`
- Open the app directory (where RimSort is)
- Open the directory RimSort keeps settings files in (and DB and instances)
- Open the RimSort logs directory
- Open the RimWorld logs directory
Did not add shortcuts for the following because they're easily reachable via settings panel:
- SteamCMD
- Steam Workshop Mods folders
- Local Mods folder
- Game mod folder
Tested on Windows and Mac

[436] adding shortcuts for opening useful directories

---

pyproject.toml

Fixes a deprecation warning with Ruff

Change deprecated extend-select to lint.extend-select

---

app/models/settings.py

Sets the default sorting algorithm to be Topological instead of Alphabetical. This change has been in discussion for a while.
The reason for making this change is twofold. Currently, Alphabetical is bugged in the sense that it does not respect certain rules when sorting. Additionally, topological as an algorithm makes more sense and is easier to maintain.
The downside is that alphabetical has been the norm for a long time. The result of this is that there may be alphabetical based sorting results that incidentally solved load order issues, but are not explicitly defined in about.xml or the community rules database. To be clear, this is not a flaw of the sorting algorithm itself. These are flaws in the rules defined that were missed.
To be clear, if someone has used RimSort already, and …

Set the default sorting algorithm to be Topological

---

app/__main__.py
distribute.py

Temporarily tell Nuitka to force enable the console on Windows. This is a temporary workaround for Nuitka issue 3019 so we can avoid downgrading Nuitka and messing with the Nuitka action.

Temporarily force windows console as workaround Nuitka bug 3019

---

.github/workflows/build.yml

- Remove console param from build action such that it defaults to whatever is set in __main__.py

Remove console param from build action

---

app/utils/schema.py

Closes #306
Patch to fix expansion disabling functionality by making it such that by default, the generate_rimworld_mods_list function handles dlc_ids/known expansions separately from packageids as a whole. In prior behavior, removing expansions from the active list also removed from knownexpansions. However, RimWorld would then forcibly add the expansion packageid into knownexpansions and the modlist.
This means that by default, the knownexpansions field of modconfig.xml will have all expansions that RimSort knows about, regardless if the user owns them, has then enabled or disabled, or if the game version predates that expansion.
Based on my testing, this behavior is fine and handled by the game. There appears to be no negative effects if knownexpansions contains packageids that the …

[306] Fix expansion disabling

---

app/views/main_content_panel.py

Adds graceful error handling for when sorting algorithm not implemented error. Warns the user with a warning dialogue instead of a fatal crash when RimSort doesn't recognize the sorting method that has been selected. The dialogue describes some potential avenues of mitigation. Mitigation is not done automatically to provide greater user control.
This is particularly useful for improper migration between versions, or from other mod managers like RimPy that happen to use the same settings file and location.

Add graceful error handling for sorting algorithm not implemented

---

app/utils/steam/webapi/wrapper.py

Fix steamDB creation crash when expiry or life is 0.
Modifies the init of the DynamicQuery class such that life must be an int (default 0). Thus, self.expiry is always set, preventing a potential crash.
Also adds docstrings to __expires

Fix steamDB creation crash when expiry or life is 0

---

app/utils/steam/browser.py

Addressing git issue #562 
From my understanding '.clear()' clears the list and all references to it while '= []' only initialized that specific list to an empty list, and did not touch any references to itself.
Issue seemed to be that here we create a reference to this list in the signal:
And it retained the old data even if the list was 'cleared'
While I did not look into it, I assume we want the same behavior for the **downloader_list_dupe_tracking** dict, so I changed it to use .clear() as well.

[562] Fixed clearing list in mod downloader

---

app/utils/watchdog.py
app/utils/win_find_steam.py

- Small change such that the windows style paths for registry keys don't trigger a linting error on linux.
- Remove watchdog type ignore

Fix minor linting errors

---

.github/release.yml

Adds a release.yml file to configure the structure and formatting of automatically generated release notes. 
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
Separates the release notes into the following categories (Note that PRs that qualify in prior categories shouldn't show up in later categories, meaning no duplicates):
🚀 Features and Improvements
- feature/improvement 🆕
- accessibility 👀 ℹ️🤓
🐛 Bug Fixes
- bugs 🪲
Miscellaneous Changes
- (All other changes not authored by dependabot)
Dependency Updates
- dependencies

Release Notes Configuration

---

.github/release.yml

dependabot exclusion didn't seem to work before. Hopefully, this fixes it.

Fix dependabot exclusion for misc changes in release notes

---

app/utils/steam/steamcmd/wrapper.py

Addressing git issue #575 
If user is reinstalling SteamCMD, ask if they want to delete and re-create the symlink.
Also added a small message to help explain what the symlink does.
I also moved the creation of a symlink into it's own method.
Changed the removal of the symlink dir to use shutil.rmtree, otherwise If a user downloaded a mod without a symlink, and then reinstalled SteamCMD and tried to 're-create symlink' it gave a non empty dir error.

[575] Re-create symlink option when reinstalling SteamCMD

---

app/utils/generic.py
app/utils/metadata.py
app/views/main_content_panel.py
app/views/mods_panel.py
tests/utils/test_generic.py

Fixes #619.
Makes it such that url parsing of http/s git urls should be much more robust. This includes the situation where the given url ends in a `/` with no other contents afterwards. Previously, that situation when parsing for the repo dir name would return an empty string as there was nothing after the last slash. These methods were factored out into generic with corresponding tests.
Additionally, the git clone action dialogue contents were improved. On bad url detection, the url is printed in the details section. On clone success, the display of the git url is not hyperlinked.

[619] Fix git url parsing, add improved git action dialogue contents, fix metadata deletion race condition crash

---

app/sort/topo_sort.py
app/utils/app_info.py
app/utils/rentry/wrapper.py
app/views/main_content_panel.py
app/views/main_window.py
requirements.txt
requirements_develop.txt

- Removed pytz from requirements as it was not being used anywhere and the library recommends that projects using 3.9 or later use the standard lib instead. https://pypi.org/project/pytz/
- Removed types-Deprecated as the Deprecated lib was not being used directly
- Replaced networkx-stubs and lxml-stubs with their typeshed equivalents
- Cleaned up and sorted requirements files
- Fixed any emerging type errors

Remove pytz and types-Deprecated, replace outdated type libs with new typeshed libs

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.vscode/settings.json

* Added links to the Wiki and Discord under the issues page.
* Improved the description for the duplicate issue affirmation
* Changed affirmation actions from checkboxes to multi-selection dropdowns. 
This is to prevent the result acting as a task item and prevent the rendering of tasks completed for created issues. Multi-selection dropdowns are utilized since this seems to be the only way to force a selection before submission for a dropdown. If it is not multi-selection, the dropdown seems to just default to the first option without input and no user action is required to pass required entry validation. This is not optimal as it requires an extra click for the user and should ideally be changed once GitHub fixes this behavior.
* Removed the default title
This is to reduce the risk of …

Improvements to GitHub Issues

---

app/__main__.py

Report RimSort version at init of application in logs at info level. Replaces the existing debug level RimSort application init log.
This is to make it a little easier to analyze user reports when logs are provided.
Example when the version is unknown:

Report RimSort version at init of application in logs

---

app/models/instance.py
app/views/main_window.py

At the initial setup of an instance, display a dialog asking if the user would like to enable steam integration. The only checks for displaying this or not are if this is initial setup of this instance, and if steam integration is already on for whatever reason (for grandfathering in existing setups). 
Internally, this introduces a new attribute at the instance level to track whenever or not this was the initial setup. At init of the object it is True, but after all setup steps in main_window, it is forced to False. The current implementation violates MVC a bit and will need to be potentially overhauled more deeply in a future refactor.
Also, improves the internals of instance's `as_dict` so it does not need to be manually expanded whenever a new attribute is added to `instance`.

Ask to enable steam integration at setup

---

app/utils/constants.py

According to the [steampage for Rimthunder - CORE](https://steamcommunity.com/sharedfiles/filedetails/?id=3070495204) it can be used as a replacement for any mods requiring Engine Industries by AOBA. Thus I added it.
Let me know if I've done something wrong, and I will try to fix it to the best of my ability. I don't know python, I just looked at the code and tried to infer what to do from that.

Add RimThunder: Core as a replacement dependency for Engine Industries by AOBA 

---

app/models/instance.py
app/models/settings.py

Fixes crash when using __setattr__ for instances, where the key does not exist.
This should fix crashes where there is an unexpected entry in the settings file for an instance. This copies the behavior for settings that are global scoped. The unexpected entry is simply ignored.

Fix crash when __setattr__ for instances, where the key does not exist.

---

app/utils/app_info.py
app/views/main_content_panel.py

Closes #679 
Adds a ```modlists``` folder to RimSort for users to store their saved modlists in.
When choosing to open or save a modlist it will default to opening this folder.

Add modlist folder to RimSort

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/pytest.yml
app/__main__.py

fixes error
FATAL: Cannot use both '--mode=' and deprecated options that specify mode.
fixes error 
E: Package 'libgl1-mesa-glx' has no installation candidate

Critical: Fix workflows

---

app/utils/rentry/wrapper.py
app/utils/steam/webapi/wrapper.py
app/views/main_content_panel.py

Fixes some unnecessary warnings when exiting import window for rentry/collection.
Also removed a duplicate warning when incorrect link was given for workshop collection.
Fixes #687

Remove warnings when exiting rentry/workshop import dialogue

---

app/utils/steam/browser.py
app/views/main_content_panel.py

Adds visual indicators in Steam Workshop browser to show which mods are already installed:
- ✓ Green checkmark for installed mods in collections
- → Blue arrow button for uninstalled mods (links to mod page)
- Green banner at the top of individual mod pages showing installation status
Closes #718 
- Collection view with checkmarks and arrows
- Individual mod page with "Already Installed" banner

Added indication of mod installation status in Workshop pages

---

app/utils/steam/browser.py

Adds a prompt when adding mods from a Steam Workshop collection, allowing users to:
- Add all mods from the collection (existing behavior)
- Add only mods that aren't already installed
Closes #720 
New dialog prompt

Add option to selectively download mods from collections

---

app/views/main_window.py

Separator was ```:``` now changed to ```|```
Had two people mention they want ```|``` vs one for ```:```
We will give this a go

Change instance name separator to |

---

app/views/main_content_panel.py
app/views/mods_panel.py

Avoids some redundant error/warning recalculations. As far as I can tell there was no need for all these recalculations. I removed some explicit triggers, and added a parameter to avoid recalculations when clearing search. All these changes seemed to have no unexpected affects on RimSorts behavior.
This just utilizes the existing logic of recalculating errors/warnings whenever a mod is inserted/removed from a list. It could be optimized further, might look into that...
Originally when clicking refresh it recalculated each list three times, now it does it once.
Originally when moving a mod from Inactive->Active through double click it recalculated each list twice, now it does it once.

Avoid some redundant error/warning recalculations

---

app/views/mods_panel.py
app/views/settings_dialog.py

1) Toggle now works for mod_type filter
2) Add Label indicating some settings require Restart of App
with "Enable mod type filter" Toggle Enabled
with "Enable mod type filter" Toggle Disabled
New Label for Advanced Settings

Minor fixes for mod_type filter

---

app/controllers/settings_controller.py
app/models/settings.py
app/views/mods_panel.py
app/views/settings_dialog.py

Enabled by default
Located in Advanced tab
If enabled it will hide invalid items when any filters are active:
Otherwise it shows them:
Behavior should apply to active and inactive modlists.

Add setting to hide invalid mods when filtering

---

app/controllers/settings_controller.py

The hide invalid mods when filtering checkbox would display itself as unchecked after a RimSort restart, although it was still on.
Great catch @LionelColaso

Make sure 'hide invalid mods when filtering' checkbox is checked/unchecked

---

docs/Gemfile.lock
docs/development-guide/development-setup.md
docs/user-guide/downloading-and-installing.md

Small update to docs to hopefully prevent some user reports in the future.
I dont have a mac, but I think the example paths are correct...

Update docs regarding macos gatekeeper

---

app/controllers/app_controller.py
app/controllers/settings_controller.py
app/controllers/theme_controller.py
app/models/settings.py
app/utils/app_info.py
app/views/settings_dialog.py
themes/Modern/style.qss
themes/Nature/style.qss
themes/SunSet/style.qss
themes/Wood/style.qss

How to add your own Themes (stylesheet)
1) Create a new folder in "themes" folder in your RimSort Config Folder
2) Using the default RimPy Theme As Refrence create your own style.qss file in the folder you created
3) Start RimSort and Select your theme from the Dropdown
4) Save settings to apply the Theme
"Note: The Name of Folder will be used as Name of the Theme / Invalid Themes will be ignored

(minor) Enable Theme Support

---

app/windows/rule_editor_panel.py

1) fix crash when "Show About.xml" is active and any column other than column3 is clicked by user 
2) add detail logging for column3 when debugging
3) avoid possible future crashes by Returning a basic editor as fallback
fixes https://discord.com/channels/1120855389651599400/1341659574310015037/1341659574310015037

rule_editor : minor bug fix update

---

app/controllers/settings_controller.py
app/views/settings_dialog.py

1) When game_folder is set "/Mods" is added to it to set local_folder
2) when game folder is cleared, it also clears local_folder
3) Removed "Choose…" and "Clear…" buttons for local_folder

Automatically set local folder from game folder and Disable Mods path selection

---

app/models/metadata/metadata_structure.py
app/utils/files.py
app/windows/rule_editor_panel.py

introduce simple UI to view existing About.XML incompatibilities - this was helpful to me to quickly check things out while debugging a crash.
Also extracts file ending search to utils for future use - I will be using it to investigate XML patch conflicts and to potentially support "cross mod compatibility warnings" like https://github.com/Ionfrigate12345/Rimworld_SOS2_VEHG_Patch/

feat: View About.XML `incompatibilities` in Rule Editor

---

app/windows/runner_panel.py

runner_panel: fix SteamCMD failing to track downloaded mods

---

app/utils/metadata.py

1) Add explicit file existence check before ACF parsing
2) Add error handling for ACF parsing failures
3) Return early on file not found or parse errors
4) Prevents potential crashes when SteamCMD ACF file is missing or corrupted.
5) Maintain existing functionality while adding safety checks
Specific error
File "views\mods_panel.py", line 1206, in eventFilter
File "utils\metadata.py", line 1382, in steamcmd_purge_mods
File "utils\steam\steamfiles\wrapper.py", line 11, in acf_to_dict
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Games\\SteamCmd\\steam\\steamapps\\workshop\\appworkshop_294100.acf'

fix and Improve SteamCMD ACF file handling

---

app/views/main_content_panel.py

Use TYPE_CHECKING to fix Repo and GitCommandError being unbound when git not available

Use TYPE_CHECKING to fix Repo and GitCommandError being unbound when git not available

---

app/views/main_content_panel.py

Simple typo that left me confused sometimes, presumably from a hasty copy & paste. Fixes #864 which I created seconds ago.

Typo fix for db merger file selection

---

app/controllers/settings_controller.py
app/models/settings.py
app/utils/gui_info.py
app/utils/steam/browser.py
app/views/file_search_dialog.py
app/views/main_window.py
app/views/settings_dialog.py
app/windows/base_mods_panel.py
app/windows/missing_dependencies_dialog.py
app/windows/rule_editor_panel.py
app/windows/runner_panel.py
app/windows/use_this_instead_panel.py

Introduce settings to configure the window size and position, along with functionality to calculate and retrieve window geometry based on the primary screen. 
This enhancement allows for a more user-friendly interface by centering the window and applying saved settings.
Should also fix 
#547

Add window size and position configuration

---

app/views/main_content_panel.py

Correct the variable name used for pushing the branch to ensure the correct branch is referenced.

Fix variable name for pushing branch to remote repository

---

app/controllers/settings_controller.py
app/controllers/sort_controller.py
app/models/settings.py
app/views/mods_panel.py
app/windows/rule_editor_panel.py

This resolves several mypy type checking issues:
1. Fixed internal mypy error in app/views/mods_panel.py by adding explicit type 
casting for QObject.findChild() method calls using typing.cast()
2. Added proper type annotations for class variables in RuleEditor class to 
resolve "Cannot determine type" errors
3. Fixed potential None/str type incompatibility in rule_editor_panel.py by 
ensuring string conversion before passing to methods that expect str
4. Format Files with Ruff

Fix Lint errors related to mypy type checking errors

---

app/utils/rentry/wrapper.py
app/views/main_content_panel.py

Rentry improvements: Now works without Rentry Auth Code and can download mods using publishfieldid as well

---

app/controllers/settings_controller.py
app/models/settings.py

Update the file dialog to open folders instead of files and adjust the default path for replacement database selection.

Fix "Use This Instead" database local selection to choose folder instead of file

---

app/controllers/settings_controller.py
app/models/settings.py
app/utils/metadata.py

Update the settings to utilize a folder path instead of a file path for the "Use This Instead" feature, ensuring consistency across the application.

Use folder path instead of file path for settings

---

.vscode/settings.json

Ensure that the default formatter for Python files is set to `charliermarsh.ruff` in the VSCode configuration.

Set default formatter for Python files in VSCode settings

---

app/controllers/main_content_controller.py
app/controllers/settings_controller.py
app/models/settings.py
app/views/main_window.py
app/views/settings_dialog.py

Introduce a setting that allows users to automatically update databases from GitHub when the application starts. This feature includes a checkbox in the settings dialog and triggers updates for various configured databases if enabled.

Add option to update databases on startup

---

app/models/settings.py
app/views/settings_dialog.py

Adjust default settings to disable database expiry, clarify notification messages, and enable warnings for duplicate mods and missing downloads.

Refactor default settings for database and mod warnings

---

app/views/settings_dialog.py

Introduce a new tab for cross-version databases in the settings dialog and reorganize existing database groups for better clarity.

Add cross-version databases tab and reorganize database groups

---

app/views/deletion_menu.py

Introduce a new action to delete selected mods and resubscribe them from the Steam Workshop. Refactor existing deletion methods for better readability and maintainability.

Add delete mod and resubscribe action to deletion menu

---

app/controllers/language_controller.py

This pull request includes a small but important change to the `language_controller.py` file. The change ensures that `.qm` files starting with `qtbase_` are excluded when retrieving language names from a folder.

Skips qtbase translation files when listing languages

---

app/utils/constants.py
app/views/main_content_panel.py

Adds metadata and package ID to support the new RimWorld Odyssey DLC.
This ensures the application correctly identifies and handles the latest expansion when processing mod data and other relevant information.

Adds support for RimWorld Odyssey DLC

---

update.bat

Sometimes, when you install Windows 11 and use a Microsoft account it decides that your username and therefore your home directory in C:\Users\ should be your full name with a space in it. The update script quotes the source directory path but not the destination, so the robocopy command fails if you have a space anywhere in the latter path.
Tested with an update from 1.0.23 to 1.0.24 on Windows 11.

Quote current directory during update on Windows

---

app/controllers/main_content_controller.py
app/utils/steam/steamcmd/wrapper.py
app/views/deletion_menu.py
app/views/main_content_panel.py
app/views/main_window.py
app/views/mods_panel.py
app/windows/runner_panel.py

This pull request refactors the codebase to improve the consistency and maintainability of message box interactions.
- Uses `QMessageBox.StandardButton` enum for button comparisons instead of string literals, enhancing code readability and type safety.
- Ensures proper translation of button texts in SteamCMD setup dialogues for improved localization support.
- Updates the dialogue response enum to use the standard button enum from `QMessageBox`, avoiding hardcoded string values.

Fixes Translations and Refactors QMessageBox usage for clarity 

---

app/utils/steam/browser.py

Hello there. o/
This is my first PR here, so let me know what I did wrong. If needed, I'm available in the discord: "`@ettykitty.`" 
At first, I wanted to leave a suggestion, but then decided to try to do it by myself, because as someone who maintains a project as well, I feel like there are always more than enough "suggestions" on your plate.
I'm not used to python at all and just a bit more used to js, and had to google every other minute, but I got it working (I hope?).
- Add "Installed" badges/markers to (duh) installed mod tiles on the items and search items workshop pages.
- I think it's pretty handy and not super intrusive.
- I'm not sure if `Feature: Check if the mod is already installed` from #406 meant what I did here. If not - let me know if I should create a separate issue as …

Add "Installed" markers to mod tiles on workshop pages

---

app/controllers/file_search_controller.py
app/utils/steam/browser.py

Improves the codebase in the following ways:
- Enhances readability in file preview generation by explicitly joining preview lines with newline characters, ensuring consistent formatting.
- Formats `browser.py` using Ruff, adhering to consistent code style guidelines.
Fixes

Fixes SyntaxError: f-string expression part cannot include a backslash

---

app/utils/steam/browser.py
app/windows/runner_panel.py
themes/Modern/style.qss
themes/Nature/style.qss
themes/RimPy/style.qss
themes/SunSet/style.qss
themes/Wood/style.qss

Hopefully, addresses things from #70.
- Make the progress bar persistent, so that the page stops changing size when it disappears.
- Remove the progress bar border, so that it doesn't look ugly always sitting on the screen.
- Reduce the progress bar height to 8 pixels, so that it takes less space.
- The % text only visible when loading.
- Smaller % font.
- Progress bar color now properly changes with the theme.
- The placeholder only showed once, when the browser is opened for the first time.
- Spent some time in the browser.
- Formatted/fixed with ruff.

feat(browser): Stop placeholder flashing; Edit the progress bar

---

app/utils/steam/browser.py

"Add to list" button is not deleted after the user opens a page of any mod and then goes back to the browse mods screen.
Caused by me forgetting that I've changed the `if` block above `else` that contains button deletion, causing it to not get executed if page = browse mods.
Now the button is deleted on every `_web_view_load_started` call. I think there is no reason not to.
Tested that the original problem is solved, and that apparently no problems with individual mod or collection "Add to list" buttons popped out - they work fine.

fix(browser): "Add to list" button getting stuck

---

app/utils/metadata.py

Adds a check to ensure that mod replacements are compatible with the current game version.
This prevents applying incompatible replacements that could lead to errors or unexpected behavior.
The check uses a regex generated from the game version to determine compatibility.

Adds game version validation for replacements

---

app/utils/steam/browser.py
app/utils/steam/js_bridge.py
app/utils/steam/setup_web_channel_script.js

- Add badges/buttons to quickly add/remove mods from the list, to mod tiles in the workshop browser.
- Supports mod tiles on collection pages as well.
- Refactor some bits of the code related to this.
- Badges:
- Hidden by default for not-installed and not-added mods, unless you hover the mod, to not clutter the UI.
- Have a minor effect when you click on them, to add responsiveness.
- Have a hover-over effect.
- JS bridge stuff:  
- Use `QWebChannel` to have a bridge between JS and python.
- No idea if this is the best way, I just found it to work, and it was the first thing I found on the internet.
- Had to manually inject `qwebchannel.js` with `QWebEngineScript`, as I have no idea how to get it to work otherwise.
- JS script stuff:
- Move the main badge/button JS script to a separate …

feat(browser): Quick add/remove buttons on tiles

---

app/views/log_reader.py
app/views/main_window.py

Adds visual highlighting to the log reader for entries associated with currently active mods.
This helps users quickly identify and focus on log entries related to mods they are actively using. It leverages a custom item delegate to apply a distinct background color and bold font to rows corresponding to active mods.
Adds a context menu option to the log reader table widget that allows users to open the URL associated with a selected mod in their default browser.
The URL is retrieved from the mod's metadata. If no URL is found, a warning is logged.

Highlights active mods and a context menu to open URL in the log reader

---

app/sort/alphabetical_sort.py
app/sort/topo_sort.py
app/utils/metadata.py
app/views/mod_info_panel.py
app/views/mods_panel.py

Improves the application's robustness by ensuring mod names and package IDs are handled as strings, preventing potential errors during sorting and display.
- Addresses potential crashes and unexpected behavior caused by non-string mod names or package IDs.
- Implements fallback mechanisms to display a generic error message when a mod name or package ID is not a string.
- Normalizes package IDs to lowercase only when they are strings.
- Converts dictionary values for mod names to string representations.

Improves robustness in mod name/package ID handling

---

app/views/acf_log_reader.py
app/views/log_reader.py
app/views/main_window.py

This pull request enhances the ACF Log Reader with a new column and clarifies existing ones.
- Renames `LogReader` to `AcfLogReader` to better reflect its purpose.
- Adds a "Mod Downloaded" column, displaying the internal timestamp of when the mod was first touched. This helps in debugging mod issues.
- Renames the "Last Updated" column to "Updated on Workshop" for better clarity.

Updates ACF Log Reader with Downloaded Timestamp

---

rimsort.nuitka-package.config.yml

- Ensures the setup script for the web channel is included in the Nuitka package configuration.
- Allows the application to properly configure the web channel when packaged with Nuitka.

Include setup_web_channel_script.js in package

---

app/controllers/main_content_controller.py
app/utils/git_utils.py

Centralized pygit2 import logic with SSL handling in `git_utils.py`.
Removed duplicate try-catch blocks.

Centralize pygit2 imports and SSL handling

---

app/views/troubleshooting_dialog.py

This PR addresses the issue where the TroubleshootingDialog content was being cut off or inaccessible on smaller screens or when users have lower resolution displays.
Closed #1055

Add scrollable content to TroubleshootingDialog

---

app/controllers/settings_controller.py
app/models/settings.py
app/views/settings_dialog.py
app/windows/base_mods_panel.py
app/windows/rule_editor_panel.py

Introduces a new checkbox in the SteamCMD settings allowing users to optionally delete mods before updating them. This ensures clean mod updates by removing old files prior to applying updates.
This feature is off by default and can be enabled in the settings

Add optional 'Delete Before Update' checkbox to SteamCMD settings

---

update.bat

Only the first `choice` was updated in the pull request #1033 . This commit updates the second, for automatic restart for french/german.
Problem adressed by @koko1ooo : https://github.com/RimSort/RimSort/issues/1051#issuecomment-3097273869
Pull request suggested by @LionelColaso : https://github.com/RimSort/RimSort/issues/1051#issuecomment-3097279270
Oddly, only the first `choice` was fixed in a pull request, but not the second. The program is updated automatically, but it doesn't restart automatically. This error only occurs when the OS language is not English, but French or German. The second `choice` is updated to include the improvements made to the first `choice`.

Fix: After an update, restart when the OS is in French/German

---

app/sort/dependencies.py
app/utils/constants.py
app/utils/metadata.py
app/windows/rule_editor_panel.py

1. Add "loadTop" to mod loading exceptions in constants.py
2. Update MetadataManager to set "loadTop" flag from community and user rules
3. Modify dependencies graph generation to include "loadTop" mods as tier one mods
4. Extend RuleEditorPanel UI with checkbox and logic to toggle "loadTop" rule

Add support for "loadTop" mod loading rule in rule_editor, metadata and sorting

---

app/sort/dependencies.py
app/utils/constants.py

1. Moved the known tier one mods set to a dedicated constant in app/utils/constants.py for better maintainability.
2. Updated app/sort/dependencies.py to use the centralized known tier one mods constant.
3. This change improves the modularity and extensibility of tier one mod handling in the dependency graph generation.

Centralize Known Tier One Mods Set

---

docs/faq.md
docs/faq.zh-cn.md

Updated the links in docs/faq.md and docs/faq.zh-cn.md to use local relative paths instead of absolute URLs.
This improves navigation within the documentation and ensures consistency across different language versions.
Specifically, links to the user guide sections for macOS workaround and databases were corrected to relative paths.

Fix relative links in FAQ documentation

---

app/sort/alphabetical_sort.py
app/sort/cycle_breaker.py
app/sort/topo_sort.py

Integrate cycle breaking in both topological and alphabetical sorting modules. Automatically detect and break known cycle between 'vanillaexpanded.vtexe.facialanims' and 'reel.facialanims'.

Add cycle breaking logic and fix circular dependency in mod sorting

---

app/views/mod_info_panel.py
tests/views/test_mod_info_panel.py

This PR introduces a new `ClickablePathLabel` class to enhance the Mod Info Panel with clickable folder paths. When the displayed path is valid and clickable, clicking it opens the corresponding folder in the system's file manager. This improves the user experience by providing direct access to mod directories.
- Added `ClickablePathLabel`, a subclass of `QLabel`, which:
- Displays the mod path with underline styling.
- Opens the directory on left mouse click if the path is valid.
- Adjusts its interactivity and cursor depending on validity.
- Replaced `QLabel` with `ClickablePathLabel` in `ModInfo` for displaying mod path.
- Adjusted style and clickability dynamically based on mod validity.
- Introduced a comprehensive test suite in `tests/views/test_mod_info_panel.py` covering:
- …

Add ClickablePathLabel for Opening Mod Folder from Mod Info Panel

---

app/controllers/language_controller.py
app/utils/generic.py

This patch introduces functionality to prompt the user to restart the application after changing the language from the settings dialog.
When the user selects a new language, it saves the setting and prompts for application restart.
Implemented a generic `restart_application()` utility in `generic.py`.
Closed #1102

feat: prompt restart on language change in settings

---

app/sort/cycle_breaker.py

Temporarily disable the removal of the dependency edge from mod_a to mod_b in break_known_cycles function by commenting out the code. This change prevents breaking cycles in one direction while still checking the reverse edge

Comment out edge removal in cycle breaker to disable breaking cycles

---

.github/workflows/auto_build.yml
.github/workflows/codeql.yml
.github/workflows/lint.yml
.github/workflows/pages.yml
.github/workflows/pytest.yml

This PR adds `merge_group` to relevant workflow files. This is intended to be preparation to enable the merge queue to improve workflows.

ci: Add merge_group to relevant workflow files

---

docs/faq.md
docs/faq.zh-cn.md

Replaced relative links in both English and Chinese FAQ documents with absolute URLs pointing to the project's GitHub Pages site. This ensures that links work correctly regardless of the current page location.

Update FAQ links to use full GitHub Pages URLs

---

app/controllers/sort_controller.py
app/sort/dependencies.py
app/sort/topo_sort.py
app/utils/constants.py

1. This PR implements a new tier zero classification for essential RimWorld mods, splitting the existing tier system into four tiers (0-3) instead of three.
2. It renames KNOWN_TIER_ONE_MODS to KNOWN_TIER_ZERO_MODS, moves 'unlimitedhugs.hugslib' to tier one.
3. Adds new core mods to tier zero and tier one.
4. It updates the sorting algorithm to handle the new tier zero dependency graph for improved mod loading granularity.
5. Updated the Doc string accordingly with examples

Introduce Tier Zero Mod Classification System

---

app/views/description_widget.py

Some mods might define colors with \" surrounding them.

Fix rendering unity rich text

---

app/controllers/menu_bar_controller.py
app/utils/event_bus.py
app/views/main_content_panel.py
app/views/menu_bar.py

Introduces `File -> Import -> From Save File...`. This will open up your saves folder and you can select a `.rws` to import. If you are subscribed to all the mods it'll just load it in the active mods list. If you're missing some mods, the missing mods modal will show up with those mods, and if you have SteamDB configured (and the mods exist in the DB), you will get the option of downloading those mods.
The functionality here is basically the same as (and ripped of from) `_do_import_list_file_xml`, which is used in the `File -> Open Mod List` feature, except this one opens the save directory. We can extract out the common code into a helper function if folks feel strongly.
Related issue: https://github.com/RimSort/RimSort/issues/1167

[1167] Import mod list from save

---

app/views/mods_panel.py

Changed the main panel layout from horizontal to vertical and introduced a dedicated horizontal layout for the mod lists. Moved the 'Use This Instead' and 'Check Dependencies' buttons from the errors summary section to a new button panel below the lists, improving UI structure and separation of concerns.
Fixes https://github.com/RimSort/RimSort/issues/1144

Refactor layout and relocate action buttons in ModsPanel

---

app/views/acf_log_reader.py
app/views/file_search_dialog.py

Address https://github.com/RimSort/RimSort/issues/1106 and https://github.com/RimSort/RimSort/issues/708.
For both the ACF Log Reader and File Search tables...
- Remove the need for a horizontal scrollbar by making the total table width always the width of the window.
- Added ability to drag to resize columns widths
- Tweaked what clicking on cell does for File Search so people can see the full cell text easily

Make Log Reader and File Search table width fixed and adjustable

---

app/controllers/metadata_db_controller.py

Was running into infinite crashes on startup. Turns out you can get in a state where SQLite fails to open the aux metadata database because the instance directory for the file (e.g., …/instances/Default/) doesn't exist yet. I updated `MetadataDbController.__init__` to create the database file’s parent directory (`mkdir(parents=True, exist_ok=True)`) before initializing the SQLAlchemy engine. This ensures the path exists and prevents the “unable to open database file” error.

Fix SQLite failing to open Aux database when it doesn't exist

---

app/views/main_content_panel.py
app/views/mods_panel.py

This speeds up scrolling down a modlist when loading new items for the first time.
For a 7k+ modlist, when launching first time this is the same speed as before while caching the folder sizes.

Speed up folder size calculation. Also cache at init/refresh

---

app/controllers/settings_controller.py
app/models/settings.py
app/views/main_content_panel.py
app/views/settings_dialog.py

Someone on the RimWorld Discord mentioned they'd like the ability for Clear to also move RimWorld DLC. Adding a toggle in Settings -> Advanced that allows you to do this.

Add option for clear to move DLC as well

---

app/controllers/main_window_controller.py
app/controllers/settings_controller.py
app/models/settings.py
app/utils/metadata.py
app/views/settings_dialog.py

Addresses https://github.com/RimSort/RimSort/issues/1150
Changes:
- ByVersion precedence: Implemented toggleable support across dependencies, incompatibilities, loadAfter/loadBefore, and description.
- ON: use matching vX.Y only; empty = no requirement; no match = fallback to base; non-additive.
- OFF: ignore all byVersion tags; use base only (preserves prior behavior).
- Safety: Guarded game version parsing and byVersion shapes; use safe `.get('li')` with empty defaults; no crashes on missing/empty tags.
- Idempotency: Dependencies, incompatibilities, and load rules use sets; no duplicates when base/byVersion overlap.
- Warnings: Aligned with toggle and precedence; byVersion empties/missing produce debug logs only; base-tag warnings unchanged.
Tested by going into some mod's About.xml, …

Add toggle for versioned About.xml tags to take precedence

---

app/controllers/settings_controller.py
app/models/settings.py
app/views/mod_info_panel.py
app/views/mods_panel.py
app/views/settings_dialog.py
tests/views/test_main_content_run.py

Introduces an option to enable or disable advanced filtering features, allowing users to control whether additional mod data (e.g. folder size, author, modified date) is shown in the mods panel. Disabling advanced filtering hides related UI elements and skips heavy calculations, addressing performance concerns for large mod sets.
(I made this an option because I don’t like it scanning the whole disk and it makes the two mod panels different in size)
https://github.com/RimSort/RimSort/pull/1190#issuecomment-3194035286

Adds toggle for advanced filtering to improve mod panel performance

---

update.bat

On Windows, Python can have a custom temporary folder set by using the system Environment Variable %TMPDIR%, this change checks if %TMPDIR% exists and if so uses it as the update_source_folder, otherwise use the regular %TEMP% path.
Resolves the issue I was having with https://github.com/RimSort/RimSort/issues/1083

Handling for custom Python temp path

---

app/utils/generic.py

Closes #998 
---
Similar to [PyInstaller](https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#launching-external-programs-from-the-frozen-application), Nuitka will also set `LD_LIBRARY_PATH` to the running application directory.
When launching applications from `subprocess.Popen`, they'll inherit RimSort's environment, including the changed `LD_LIBRARY_PATH`.
This can cause issues when launching external applications (like KDE's xdg-open) due to conflicts with system Qt6 and PySide bundled Qt6, since applications will try to load libQt6Core (and other libs) from RimSorts directory instead.
Unlike PyInstaller however, there's not a "backup" `LD_LIBRARY_PATH_ORIG` to resture the value from, so we just reset it to empty when launching xdg-open

Launch xdg-open with a clean environment

---

app/views/mods_panel.py

Add type annotation for new_mod_color_name variable in handle_mod_color_change method 
Add safety check to ensure new_mod_color_name is not None before updating Aux DB Initialize invalid_color and new_color variables in eventFilter for color picker logic

Fix mod color handling and add safety checks

---

app/windows/runner_panel.py

Add self.close() call in _handle_steamcmd_completion method to close the runner panel immediately after emitting the redownload signal. This prevents user interaction with the panel during the ongoing download process.

Close RunnerPanel after initiating redownload

---

app/views/mods_panel.py

Sets 'use_this_instead' in mod_errors when an alternative mod is recommended, improving error reporting and tooltip messaging for outdated mods.
Also, now shows warning and error panel correctly with proper mods count
Before
Now

Add 'use_this_instead' flag for alternative mods

---

app/utils/constants.py

Expanded the KNOWN_MOD_REPLACEMENTS for 'brrainz.harmony' to include 'jikulopo.prepatcher' alongside 'zetrith.prepatcher'. This helps improve mod compatibility handling.

Add jikulopo.prepatcher to Harmony mod replacements

---

tests/views/test_main_content_run.py

Introduced an unsaved_main_content fixture to centralize the setup of unsaved changes for tests related to running with unsaved modifications. This reduces code duplication and improves test maintainability.

Refactor unsaved state setup in run tests

---

app/controllers/settings_controller.py
app/models/settings.py
app/utils/update_utils.py
app/views/settings_dialog.py

- Call _cleanup_old_backups at start of do_check_for_update to remove old backups before update check.
- Add enable_backup_before_update and max_backups settings with UI controls in settings dialog.
- Update settings controller to sync new backup settings.
- Remove user prompt for backup creation; use settings flag instead.
- Keep only max_backups most recent backups, deleting older ones automatically.

Add backup cleanup in update process and settings UI

---

app/utils/xml.py
pyproject.toml
uv.lock

- Remove xmltodict dependency from pyproject.toml and uv.lock
- Implement custom etree_to_dict and dict_to_etree functions for XML/dict conversion
- Update xml_path_to_json and json_to_xml_write to use xml.etree.ElementTree
- Keep BeautifulSoup as fallback for complex XML parsing
- Update docstrings to accurately reflect dictionary handling
- Maintain compatibility with gzip and zstd compressed files

Refactor XML utilities to use standard library xml.etree.ElementTree instead of xmltodict
