RimSort/RimSort

util/mods.py, util/xml.py
=> Add multi-case check for About.xml resolution & improved debugging

data/style.qss, model/mod_list.py, model/scroll_label.py, panel/mod_info_panel.py, util/mods.py, view/main_content_panel.py
Adding functionality to show information about a mod when that mod if clicked on in either mod list. Easily editable to show more/less information.
=> adding mod info panel functionality

util/steam/steamcmd/wrapper.py, window/runner_panel.py
Added a progress bar for the runner of steamcmd on top of the screen as it was confusing at when it ends
=> Added a progress bar for steamcmd runner

window/runner_panel.py
fix status  & steamcmd crashing on windows when dl mods
=> Fixes for SteamCMD downloader & status

.gitignore, model/dialogue.py, model/mod_list.py, model/scroll_label.py, sort/rimpy_sort.py, sub_view/actions_panel.py, sub_view/active_mods_panel.py, util/generic.py, util/steam/browser.py, view/game_configuration_panel.py, view/main_content_panel.py, window/settings_panel.py
- Fix Typos
- Add ability to toggle warnings (#69 )
- add "Upload RimWorld log" button to actions panel
- Prohibit game or DLC deletion (core + dlcs)
- Fix issues with browser when a site tries to open a link in a new tab
=> Cherry picks

docs/wiki/Development Guide.md
a mini typo fixed and added line to feature suggestions
=> Update Development Guide.md

window/settings_panel.py
=> Fix RimSort Log Upload

model/mod_list_item.py, sub_view/mod_info_panel.py
Seems like it Does not Like Upper Case Characters
=> FIX: RimSort isn't picking mod's version information #162

view/main_content_panel.py
=> Added is-not-none check before check_if_pfids_blacklisted

docs/wiki/User Guide.md
Previews for Windows and Mac users are added in docs/wiki/users like we have discussed in the discord chat also see comment #184
=> Wiki previews

RimSort.py, controller/settings_controller.py, model/settings.py, requirements.txt, util/app_info.py, util/event_bus.py
- Also added an AppInfo singleton class to handle app metadata, in this case specifically the platform-dependent location of the settings file
- Also added an EventBus singleton class to facilitate loose coupling between objects that send signals and objects that receive signals; Settings sends a signal through the event bus when app settings have changed
=> Extend Settings model to include all application settings

RimSort.py, controller/menu_bar_controller.py, controller/settings_controller.py, model/mod_list.py, model/settings.py, sub_view/active_mods_panel.py, sub_view/inactive_mods_panel.py, util/metadata.py, view/game_configuration_panel.py, view/main_content_panel.py
Pieces of data that were previously stored on the GameConfiguration class have been moved to the Settings class, accessed through the SettingsController. The Settings class is now responsible for reading and parsing the `settings.json` file, for storing its data, and for writing that file back out to disk as needed. The following settings are implemented:
- check_for_update_startup
- show_folder_rows
- sorting_algorithm
- external_steam_metadata_file_path
- external_steam_metadata_repo
- external_steam_metadata_source
- external_community_rules_file_path
- external_community_rules_repo
- external_community_rules_metadata_source
- db_builder_include
- database_expiry
- build_steam_database_dlc_data
- build_steam_database_update_toggle
- watchdog_toggle
- mod_type_filter_toggle
- …
=> Refactor application to use SettingsController

RimSort.py, model/mod_list.py, model/mod_list_item.py, model/multibutton.py, sub_view/actions_panel.py, sub_view/active_mods_panel.py, sub_view/inactive_mods_panel.py, themes/Ash/style.qss, themes/Bright/style.qss, themes/Charcoal/style.qss, themes/RimPy/style.qss, view/main_content_panel.py, window/runner_panel.py, window/settings_panel.py
- Additionally replaces `setStyleSheet` calls with actual references in the stylesheet.
=> Fix data source filter while searching. New themes in prep for ThemeManager

controller/settings_controller.py
Added conditional logic to SettingsController to handle the game location "Choose…" click handler differently on Macs and non-Macs. On Macs, the user is prompted to choose a file (the game) while on non-Macs the user is prompted to choose a directory (the folder enclosing the game).
=> Implement different choose-game-location logic on Mac and non-Mac

controller/app_controller.py, requirements.txt
- Also upgrade PySide6 requirement to version 6.6.0 to get bug fixes and new features, most importantly support for the OS-level light/dark appearance preference
=> Change app style to "Fusion" for all OS's and apply default (currently empty) stylesheet

controller/menu_bar_controller.py, util/event_bus.py, util/metadata.py, util/rentry/wrapper.py, view/main_content_panel.py, view/menu_bar.py
also checks one of the import options in https://github.com/RimSort/RimSort/issues/56
=> import modlist from Rentry.co link

RimSort/views/main_content_panel.py
=> Implement _on_do_download_all_mods… methods

app/controllers/settings_controller.py
This whole method needs a good refactoring, but for now this change fixes the crasher.
=> Minimal fix of app crash on paths autodetect

app/controllers/menu_bar_controller.py, app/utils/event_bus.py, app/utils/rentry/wrapper.py, app/utils/steam/webapi/wrapper.py, app/views/main_content_panel.py, app/views/menu_bar.py
Sorta copied the dialog from RentryImport
We should standardize that later, along with our QMessageBox usage (we already have show_dialogue_yaddayadda)
=> Add ability to import mod list from workshop collection

docs/wiki/User Guide.md
- https://github.com/RimSort/RimSort/wiki/User-Guide#external-metadata  downloaded downloaded; removed the extra downloaded from the sentence and added a period at the end of a sentence that was not ended in a period.
=> Update User Guide.md

app/windows/workshop_mod_updater_panel.py
I always feel I need to select all and update selected mods. Then I realized maybe we need an "update all" button!
=> Add an "Update all" button in the mod updater panel

app/views/main_content_panel.py, app/views/mods_panel.py
Hi! 
This PR sorted the inactive mod list by mod names alphabetically.
Use case:
Sometimes I decide to add a few faction mods I love to my mod list, however, I have no idea what my loved mods are, I will need to go through the mods one by one to choose the ones I love. One issue is the default order is not alphabetically on mod names, so when I scanned through the list, I have to think: did I visit this already? Did I love it and do I need this extension mod? This is very annoying. After a quick search in the issue tracker, I found the following issue.
https://github.com/RimSort/RimSort/issues/131#issue-1784694223
This PR provides a simple way to sort the ModsPanel with a custom function recreate_mod_list_and_sort
Edits:
1. app/views/mods_panel.py: function uuid_to_mod_name
- input uuid …
=> Sorting inactive mod list alphabetically

app/views/main_content_panel.py, app/views/mods_panel.py
=> Fix Merge Conflicts

app/views/mods_panel.py
This is related to issue #137 and I'm having the screenshot here and there.
=> Make mods name text that not compatible with game version in Red

app/views/mods_panel.py
This is a temp branch I created to merge my fork for #137 
I just realized I don't need to create a seperate branch for this.
=> Merging temp branch to main

app/sort/dependencies.py, app/utils/constants.py, app/utils/metadata.py
Hi! I just updated some constants to support the newly out DLC Anomaly. Hope I'm doing it correctly.
I've edited 3 places of constants in `constants.py` `metadata.py` and `dependencies.py`.
Currently I'm running it with no problem.
Please stress test it and merge it when ready.
=> update some constants to support DLC4 Anomaly

app/controllers/settings_controller.py, app/views/settings_dialog.py
https://github.com/RimSort/RimSort/issues/235
=> Add Clear Button for location Tab

requirements.txt
After a very long time finally now everything runs > builds and runs on Pyside6 v 6.7.0
=> update pyside6  to version 6.7.0

app/views/main_content_panel.py, app/views/mods_panel.py
File "E:\Github\RimSort_Lion\build\__main__.dist\app\views\mods_panel.py", line 994, in eventFilter
AttributeError: 'PySide6.QtGui.QInputEvent' object has no attribute 'pos'
=> Fix object has no attribute 'pos'

app/views/main_content_panel.py
Improves URL substring sanitization.
Not really required for our use case in terms of security, but is accepted practice.
=> improved URL substring sanitization

app/views/main_window.py
=> fix error while creating new instance

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/lint.yml, .github/workflows/test_builds.yml, .vscode/settings.json, CODE_OF_CONDUCT.md, LICENSE.md, README.md, update.sh
Linting fixes for non-python related things
=> Non python lint fixes

app/views/mods_panel.py
Fixes #360 
Also small fix to add type annotations to count_icons
=> Prevent warning icon label from showing before it has a parent (#360)

.github/workflows/lint.yml, .jscpd.json, pyproject.toml
=> Don't lint inside submodules

app/utils/generic.py, app/views/main_content_panel.py
Improved error handling and reporting for 0x0.st
Also, slightly refactored to avoid duplicate code in main_content_panel when calling 0x0 related methods. Also implements threading such that the application doesn't freeze if it takes a while to upload the log.
Fixes #444
=> Refactored 0x0.st upload for threading and error handling

app/views/mods_panel.py
=> fix crash when mod name is none

app/views/main_content_panel.py
Some typing fixes for main_content_panel.py
Fixes almost all typing fixes.
Dependent on #441
=> Main content panel typing fixes

app/models/animations.py
Minor fixes pertaining to typing and also QT class creation for the animations.py file.
=> Refactor AnimationLabel and LoadingAnimation classes

app/views/mods_panel.py
Adding tooltips for active and inactive mod list filter mode icons
For https://github.com/RimSort/RimSort/issues/483
=> [483] tooltips for filter mode icons

app/controllers/settings_controller.py, app/models/settings.py, app/utils/metadata.py, app/views/settings_dialog.py
Moving This since it makes more sense here
=> Move Workshop database expiry to Database Tab

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Fixes the template labels so that the two types hopefully have correct labels automatically assigned such that it is easier to differentiate between the two.
=> Fix template labels

app/controllers/settings_controller.py, app/views/settings_dialog.py
1) Rearranged some Buttons
2) Added Warning Texts to Build Database Tab
=> Minor Setting Changes

app/views/main_content_panel.py
Fixes a crash that occurs when trying to update a git mod.
=> Fix git update crash

app/views/settings_dialog.py
=> database_expiry_label Spelling fix

app/utils/generic.py, app/utils/todds/wrapper.py, app/views/main_content_panel.py
- Forces the paths passed to todds to be absolute
- Sets the process working directory of RimWorld to be the game target location
=> Improves relative path handling for todds and game launch

app/controllers/mods_panel_controller.py, app/models/animations.py, app/sort/topo_sort.py, app/utils/metadata.py, app/utils/steam/browser.py, app/views/main_content_panel.py, app/views/mods_panel.py, app/windows/missing_mods_panel.py
Argument name and Variable in function should be lowercase
Fixes Local variable 'package_id' might be referenced before assignment
It is needlessly complex to invert the result of a boolean comparison.
=> Minor fixes

app/windows/runner_panel.py
Added Operation Completed Notification to runner_pannel to let user know its safe to close the window
=> Add completion notification  to runner panel

app/views/main_window.py
Closes #658 
Should look something like this:
=> Add instance name to main window title

app/__main__.py
Hello i use is to try to make a flatpak with 
- install -D app/__main__.py /app/bin/RimSort
and i think its usesfull for all
Thanks !
=> Add Python shebang to main.py

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .gitmodules, README.md, app/controllers/menu_bar_controller.py
Updates wiki links
- Read Me
- Issues Templates
- Issues Page
- App Wiki Link
Also cleans out the wiki entry in .gitmodule
=> [608] Update Wiki Links

.github/workflows/build.yml, app/__main__.py
Fix fatal build error by only using mode and removing related deprecated options
=> Fix Nuikta Build Options - Only use mode and remove deprecated options

app/utils/rentry/wrapper.py
=> rentry: avoid crashes

app/views/mods_panel.py
* "C# mod icon" + Tooltip
* "XML mod icon" + Tooltip
* Icons as per state + Tooltip
=> [145] Implement "mod type filter"

app/controllers/menu_bar_controller.py, app/utils/event_bus.py, app/views/main_content_panel.py, app/views/menu_bar.py
Root Directory
Config Directory
Local Mods Directory
Steam Mods Directory
RimSort
RimWorld
=> [513] Additional Shortcuts and Improved Organization

app/views/main_content_panel.py
Handle the unlikely git dubious owner error.
=> Fix git dubious owner error

app/views/main_content_panel.py
=> Fix todds doesn't optimize Steam mods

app/utils/steam/browser.py
=> Fix indication of mod installation status in Workshop pages

app/controllers/mods_panel_controller.py, app/views/mods_panel.py
Updates count when any filters are active, not just search.
=> Update mod counts when using any filters

app/windows/missing_mods_panel.py
Fixes mod download due to incorrect column selection
=> fix missing mods panel unable to download mod

app/views/main_content_panel.py, app/views/mods_panel.py
=> Fix re_steamcmd_action

app/views/main_content_panel.py
Use TYPE_CHECKING to fix Repo and GitCommandError being unbound
=> fix Repo and GitCommandError being unbound

app/utils/app_info.py, app/utils/constants.py, app/utils/custom_qlabels.py, app/utils/generic.py, app/utils/rentry/wrapper.py, app/views/log_reader.py, app/views/main_window.py
Functional Basic "Acf Data Reader" can be used to check mod Update logs
Works with SteamCMD
=> log reader

app/controllers/menu_bar_controller.py, app/controllers/troubleshooting_controller.py, app/views/main_window.py, app/views/menu_bar.py, app/views/troubleshooting_dialog.py, tests/conftest.py, tests/controllers/test_troubleshooting.py
=> Troubleshooting tab

app/windows/use_this_instead_panel.py
Fix KeyError in UseThisInsteadPanel when 'authors' or 'name' keys are None
fixes #830
=> Fix KeyError in UseThisInsteadPanel when 'authors' or 'name' keys are None

requirements.txt
Fix For Windows10 Related issues for more see https://bugreports.qt.io/browse/QTBUG-134746
#814
#829
=> downgrade pyside6 to fix Windows !0 related issues

app/views/log_reader.py, app/views/main_window.py
=> Acf log reader

app/utils/mod_utils.py, app/views/log_reader.py
1) now uses mod_utils to get mod name and path
2) improve performance by delayed loading of acf data 
3) only updates table if acf file change is detected, which improves performance 
4) enables and disables buttons based on task
5) improve logging
=> log_reader: Refactor

app/controllers/menu_bar_controller.py, app/models/settings.py, app/views/main_content_panel.py, app/views/menu_bar.py
Notifies user when update is available
Auto update check on startup is enabled by default
=> Add Update Menu to check for RimSort updates

app/views/main_content_panel.py
Fixes https://discord.com/channels/1120855389651599400/1371014925429903410
=> fix crash when KeyError: 'tag_name' is None

app/controllers/app_controller.py, app/controllers/settings_controller.py, app/controllers/theme_controller.py, app/models/settings.py, app/views/settings_dialog.py
This pull request introduces font customization capabilities to the application, allowing users to select a font family and size for the UI. The changes span multiple files and include updates to the settings model, theme controller, and settings dialog UI.
* **Font Settings in Theme Controller**:
- Added `font_family` and `font_size` attributes to `ThemeController` with default values. (`app/controllers/theme_controller.py`, [app/controllers/theme_controller.pyR30-R31](diffhunk://#diff-276c2c8ced8d6939f353484c4893972ea88d916114fec77c95579b054d797dbfR30-R31))
- Introduced a `set_font` method to update font settings and modified `load_theme` to include font styles in the theme stylesheet. (`app/controllers/theme_controller.py`, [[1]](diffhunk://#diff-276c2c8ced8d6939f353484c4893972ea88d9161 …
=> Add support for custom font settings

app/views/settings_dialog.py, app/windows/missing_dependencies_dialog.py, themes/Modern/style.qss, themes/Nature/style.qss, themes/RimPy/style.qss, themes/SunSet/style.qss, themes/Wood/style.qss
1) Fixed improper display of windows_size_group_label
2) Updated missing_dependencies_dialog widgets and layout 
3) Added Theme Support for
=> Theme Update

app/views/mods_panel.py
fix: update tooltip text for mod loading errors to English
=> Fix: Revert unintended text changes

app/utils/gui_info.py
The changes ensure that calculated window geometry is saved persistently.
=> Fix window geometry inconsistency by saving calculated defaults

app/utils/steam/browser.py
=> Added fallback HTML scraping for collection mods in SteamBrowser

README.md, docs/development-guide/translation-guide.md, docs/development-guide/translation-guide.zh-cn.md, translation_helper.py
This pull request introduces comprehensive documentation for contributing translations to the RimSort project.
=> Add Translation Contribution Guidelines

app/windows/runner_panel.py
Enhance the RunnerPanel by using Optional types for parameters, improving process termination logic, and refining output handling. Add detailed logging for better traceability and refactor UI setup methods for improved readability.
=> Refactor RunnerPanel for improved initialization and process management

requirements.txt
Add certifi dependency to requirements its required by requests module
=> Add certifi dependency to requirements

distribute.py
Initialize variables in the `copy_swp_libs` and `get_latest_todds_release` functions to improve code clarity and maintainability.
=> Refactor variable initialization in functions

requirements_develop.txt
Include Pylance in the development requirements for improved type checking and IntelliSense support.
=> Add Pylance to development requirements

app/utils/git_utils.py, app/utils/git_worker.py
This pull request introduces enhancements to Git operation handling, focusing on adding timeout configurations, improving error handling, and enabling operation interruption in worker threads. These changes aim to make Git operations more robust and responsive, especially in scenarios involving network latency or user cancellations.
=> Add network and timeout handling to Git operations

.vscode/settings.json
Adds YAML formatting support to the project.
- Configures VS Code to use the Red Hat YAML extension for formatting YAML files.
- Improves code consistency and readability for YAML files.
=> Adds YAML formatting support

app/views/main_content_panel.py, requirements.txt, rimsort.nuitka-package.config.yml, update.bat, update.sh
This pull request refactors and enhances the application update process to improve reliability and user experience.
Key changes include:
- Fetches release information from the GitHub API.
- Validates versions to ensure updates are applicable.
- Provides platform-specific downloads for compatibility.
- Implements enhanced error handling.
- Adds a download progress indicator.
- Extracts updates to a temporary directory.
- Launches an update script to finalize the process.
- Adds file to nuitka config
- Updates the update script for both windows and unix to ensure a more robust and safer experience.
- Adds `packaging` library to requirements.txt
Tested and Works on  "Windows-11" and "Ubuntu-24.04"
=> Add Ability to Update RimSort

app/controllers/main_content_controller.py, app/utils/git_utils.py, app/utils/git_worker.py
This PR enhances the git update functionality with better user feedback and fixes a critical thread blocking issue.
1. Now shows the latest commit information (hash + message) for successfully updated repositories
2. Replaced UI dialog calls with logging for merge conflicts to prevent thread blocking
=> feat: Enhanced Git Update UI with Commit Info and Thread Safety Improvements

app/views/deletion_menu.py
This PR improves translation handling for deletion dialog.
=> Improve translation handling for deletion dialog

update.bat
Improves the RimSort update process for better reliability and user experience.
Key changes include:
- Enhanced error handling to address potential issues during the update.
- Implements a more robust backup procedure before updating, ensuring data safety.
- Provides clearer user feedback throughout the update process.
- Verifies the updated executable after the update to ensure a successful installation.
- Streamlines temporary file cleanup.
- Introduces timestamping to backup folder names for better organization.
=> Improves RimSort update process reliability on Windows

update.bat
Fix sintax errors.
Fix for the bug issue created by me: https://github.com/RimSort/RimSort/issues/1032
=> Fix Update.bat

app/views/log_reader.py
Improves the Log Reader's user interface and reduces unnecessary log output.
- Prevents redundant "ACF path is None" warnings during initial application load, reducing log clutter.
- Combines the "Last Updated" and "Relative Time" columns into a single column for improved UI clarity.
- Adds automatic descending sorting by the "Last Updated" column on initial load.
=> Improves Log Reader UI and Reduces Log Clutter

app/controllers/troubleshooting_controller.py, app/utils/gui_info.py
=> fix: improve mod list export error handling

app/views/troubleshooting_dialog.py, themes/Modern/style.qss, themes/Nature/style.qss, themes/RimPy/style.qss, themes/SunSet/style.qss, themes/Wood/style.qss
This pull request refactors the `TroubleshootingDialog` to modernize the UI, improve user experience, and enhance maintainability.
=> Refactor TroubleshootingDialog UI for Enhanced Design and Usability

app/views/main_content_panel.py, themes/Modern/style.qss, themes/Nature/style.qss, themes/RimPy/style.qss, themes/SunSet/style.qss, themes/Wood/style.qss
=> Add the ability to resize parts of the interface

app/sort/topo_sort.py, pyproject.toml, uv.lock
Attempt number two to fix flaky linter complaints.
=> fix: Remove networkx-stubs dependency

app/views/main_content_panel.py
Added file extension check to ensure only .zip files are considered Improved handling of asset names that might be lists Refined platform and architecture matching logic
Enhanced fallback mechanism to include extension check
=> Improve asset matching logic for update downloads

distribute.py
For some unknown reason, using Nuitka prefixes and postfixes, you can't directly specify `SteamworksPy.dylib`. If you do prefix `SteamworksPy` it won't work because it'll include the wrong processor when building for the other processor. I don't feel like changing [SteamworksPy itself](https://github.com/philippj/SteamworksPy/blob/master/steamworks/__init__.py#L78), so here's a brute force way of resolving the issue-- after building, copy the processor-postfixed `SteamworksPy*.dylib` to `SteamworksPy.dylib`.
This seems to work, putting `SteamworksPy.dylib` in the app (along with the processor-postfixed one), and SteamCMD actions work now + no more "missing SteamworksPy.dylib" exceptions.
Open to other suggestions.
=> [789] forcibly add steamworks.dylib into mac build

.github/workflows/build.yml
Attempting to add the LICENSE.md content as the EULA for Windows .msi setup
=> Add LICENSE content as Windows MSI EULA

app/utils/metadata.py
For core/DLC, name was only supplemented during the post-batch expansion step, so any single-file re-parse triggered by the watcher (while RimWorld/RimSort runs) could revert the name back to the placeholder.
The potential fix explored here is moving DLC/Core name normalization into a new helper (`supplement_dlc_metadata`) and then calling it from `compile_metadata` for each UUID. I also removed the previous special-case expansion supplement from `__refresh_internal_metadata` to keep a single source of truth.
`compile_metadata` runs for both full refreshes and targeted updates, so DLC/Core entries are normalized immediately after any re-parse. This *should* eliminate the regression path and ensure stable names without race or duplication.
**IMPORTANTLY,** I can't actually test this on my …
=> Possible fix for core/DLC missing XML

app/views/settings_dialog.py
=> Move Aux DB settings to their own tab

app/views/mods_panel.py
I broke it, so im fixing it. This is still slightly faster than original from short testing.
=> Fix folder size calculation

data/RimSort.wxs
=> Update D drive check to ensure accessibility for installation

app/models/settings.py, app/views/main_window.py, app/views/player_log_tab.py
Introduces a new Player Log tab to the main window, providing real-time log monitoring, advanced filtering, search, highlighting, statistics, and export capabilities. Updates settings to support auto-loading the player log on startup and integrates the new tab into the main UI.
=> Add Player Log tab with advanced log viewing features

app/controllers/main_window_controller.py, app/controllers/settings_controller.py, app/models/settings.py, app/sort/dependencies.py, app/utils/metadata.py, app/views/mods_panel.py, app/views/settings_dialog.py
Improve the organization and clarity of the settings dialog by restructuring XML parsing and dependency handling options. Update default settings to enhance dependency resolution and tag precedence.
=> Refactor settings for clarity and organization

app/controllers/metadata_db_controller.py
Fixes race condition in AuxMetadataController.get_or_create method by handling concurrent insertions gracefully. The method now catches IntegrityError, rolls back, and queries again for the existing entry.
tried to fix error https://0x0.st/KqUB.log
=> Fix SQLite IntegrityError in get_or_create

app/sort/topo_sort.py
- Sort mods within topological levels by packageid instead of name for consistent load order
- Add error handling for missing packageid in metadata with warning logs
- Optimize dict lookups by building both uuid-to-packageid and packageid-to-uuid mappings
- Use list comprehensions for cleaner and more efficient code
- Ensure stable sorting by using packageid.lower() as sort key
=> Improve do_topo_sort consistency and robustness

app/__main__.py, app/controllers/app_controller.py, app/controllers/language_controller.py, app/utils/app_info.py, distribute.py
1. This pull request refactors the language data folder access in the RimSort application to use a property for better encapsulation and maintainability.
2. It updates the LanguageController and AppController to utilize this new property, improving code clarity and consistency.
3. Additionally, it fixes a Pylance warning related to a possibly unbound app_controller variable.
4. The PR also adds the --include-data-dir option for qtwebengine_locales to ensure proper inclusion of Qt WebEngine translation files, addressing localization issues in the UI.
Changes include:
- Refactoring language data folder access to use a property in app/utils/app_info.py
- Updating LanguageController to use the new language_data_folder property
- Fixing Pylance warning for app_controller in app/main.py
- …
=> Refactor Language Data Access and Improve Qt WebEngine Locale Inclusion

distribute.py
=> fix path name

app/views/deletion_menu.py, tests/views/test_deletion_menu.py
- This PR refactors the ModDeletionMenu class in app/views/deletion_menu.py to improve code organization, error handling, and maintainability. Key improvements include:
1. Modularized deletion operations: Introduced a generic _perform_deletion_operation method to handle various deletion types (complete deletion, DDS-only deletion, selective deletion) with consistent confirmation dialogs and progress tracking.
2. Enhanced error handling: Split mod processing into smaller, more robust methods (_process_single_mod_deletion, _execute_deletion_operation) with specific exception handling for file system errors, data validation issues, and unexpected errors.
3. Improved logging and progress tracking: Added detailed logging for deletion operations, including progress percentages and summary …
=> Refactor ModDeletionMenu class with enhanced error handling, logging, and comprehensive tests

docs/development-guide/translation-guide.md, docs/development-guide/translation-guide.zh-cn.md
- Add detailed command descriptions and examples for translation_helper.py
- Update supported languages table with new complete translations
- Expand Translation Helper Tool section with features and usage examples
- Update Quick Start guide to include auto-translate step
=> Update translation guides to reflect translation_helper.py enhancements
